// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epmrcxyxnykiykuzqqje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwbXJjeHl4bnlraXlrdXpxcWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NzI0NjEsImV4cCI6MjA1NjA0ODQ2MX0.lp7veFcY8uEtYL87SGaLSM_UzcEPDdml_23ZxmIs2D8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);